from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
    "mvn versions:set -DnewVersion={{version}}",
    "yq '.version=\"{{version}}\" | .appVersion=\"{{version}}\"' deployment/helm/Chart.yaml"
]
post_bump_hooks = [
    "git push",
    "git push origin {{version}}"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "witcom-api-gateway"
owner = "witcom-gmbh"
authors = [
    { signature = "Carsten Buchberger", username = "iceman91176" }
]

[bump_profiles]

[packages]
