from_latest_tag = false
ignore_merge_commits = true
branch_whitelist = ["main"]
pre_bump_hooks = [
    "mvn versions:set -DnewVersion={{version}}",
    "yq -i '.version=\"{{version}}\" | .appVersion=\"{{version}}\"' deployment/helm/Chart.yaml"
]
post_bump_hooks = [
    "git push",
    "git push origin {{version}}"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[commit_types]
improvement = { changelog_title = "Improvements", bump_patch = true }
chore = { changelog_title = "Chore", omit_from_changelog = true }
ci = { changelog_title = "", omit_from_changelog = true }
perf = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "witcom-api-gateway"
owner = "witcom-gmbh"
authors = [
    { signature = "Carsten Buchberger", username = "iceman91176" }
]

[bump_profiles]

[packages]
