apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: witcom-api-gateway
  name: witcom-api-gateway-runtime
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    pushSecret:
      name: nexus-dev
    to:
      kind: DockerImage
      name: 'pub-registry.dev.witcom.services/witcom/witcom-api-gateway:test'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: >-
      FROM
      docker-registry.default.svc:5000/openshift/springboot-java-run:openjdk11
      
      COPY app.jar /opt/openshift/app.jar
      
      CMD ["./run"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      env:
        - name: MAVEN_ARGS_APPEND
          value: '-Pprod'
      from:
        kind: ImageStreamTag
        name: 'springboot-java-run:openjdk11'
        namespace: openshift
    type: Docker
  successfulBuildsHistoryLimit: 5