apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "witcom-api-gateway.fullname" . }}
  labels:
    {{- include "witcom-api-gateway.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "witcom-api-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "witcom-api-gateway.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "witcom-api-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: COMMAND_ENABLED
              value: {{ .Values.config.command.enabled | default "true" | quote }}
            - name: COMMAND_BASE_URL
              value: {{ required "A valid config.command.baseUrl entry is required!" .Values.config.command.baseUrl }}
            - name: COMMAND_USER
              value: {{ required "A valid config.command.user entry is required!" .Values.config.command.user }}
            - name: COMMAND_GROUP
              value: {{ required "A valid config.command.group entry is required!" .Values.config.command.group }}
            - name: COMMAND_TENANT
              value: {{ required "A valid config.command.tenant entry is required!" .Values.config.command.tenant }}
            - name: KEYCLOAK_SERVER_URL
              value: {{ required "A valid config.keycloak.serverUrl entry is required!" .Values.config.keycloak.serverUrl }}
            - name: KEYCLOAK_REALM_ID
              value: {{ required "A valid config.keycloak.realm entry is required!" .Values.config.keycloak.realm }}
            - name: COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.config.command.passwordSecretKey | default "password" }}
                  name: {{ required "A valid config.command.passwordSecret entry is required!" .Values.config.command.passwordSecret }}
            {{- if .Values.config.redis.secret.name }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.config.redis.secret.key }} 
                  name: {{ .Values.config.redis.secret.name }}
            {{- end }}
            - name: REDIS_HOST
              value: {{ required "A valid config.redis.host entry is required!" .Values.config.redis.host }}
            {{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /gateway/health
              port: http
          readinessProbe:
            httpGet:
              path: /gateway/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
