spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
  config:
    import: "consul:"
  cloud:
    consul:
      discovery:
        enabled: false
      port: 443
      scheme:  http                      
      config:
        enabled: true
        fail-fast: true
        prefix: applicationconfig
        format: yaml
        profile-separator: "::"
    