#spring.cloud.gateway.httpclient.ssl.use-insecure-trust-manager
#feign:
#  client:
#    config:
#      default:
#        logger-level: full
        
spring:
  redis:
    host: redis
    port: 6379

  cloud:
    consul:
      discovery:
        enabled: false
      port: 443
      scheme:  http                      
      config:
        enabled: false

    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"          
      routes:
#service-planet default-tenant    
      - id: spl
        uri: ${application.spl-config.tenants[0].spl-base-url}/serviceplanet/remote/service
        predicates:
         - Path=/smdb/**
        filters:
#         - KeyCloakFilter=requiredRole,service_read
         - ServicePlanetFilter
         - RewritePath=/smdb/(?<segment>.*), /serviceplanet/remote/service/$\{segment}
#service-planet default-tenant    
      - id: spl-other-tenant
        uri: ${application.spl-config.tenants[0].spl-base-url}/serviceplanet/remote/service
        predicates:
         - Path=/smdb-tenant-2/**
        filters:
#         - KeyCloakFilter=requiredRole,service_read
         - name: ServicePlanetFilter
           args:
             tenant: TEST01
         - RewritePath=/smdb-tenant-2/(?<segment>.*), /serviceplanet/remote/service/$\{segment}
#service-planet default-tenant    
      - id: spl-different-tenant
        uri: ${application.spl-config.tenants[1].spl-base-url}/serviceplanet/remote/service
        predicates:
         - Path=/smdb-tenant-3/**
        filters:
#         - KeyCloakFilter=requiredRole,service_read
         - name: ServicePlanetFilter
           args:
             tenant: TEST02
         - RewritePath=/smdb-tenant-3/(?<segment>.*), /serviceplanet/remote/service/$\{segment}

#dsl recherche
      - id: dsl-api
        uri: https://secure.mk-netzdienste.de/kundenportal
        predicates:
         - Path=/dslrecherche/**
        filters:
          - KeyCloakFilter=requiredRole,service_read
          - RemoveRequestHeader=Authorization    
          - BasicAuthFilter=${MK_USER},${MK_PASS}
          - RewritePath=/dslrecherche/(?<segment>.*), /kundenportal/$\{segment}
#camunda
      - id: camunda-rest-api
        uri: http://camundaengine:8080/engine-rest
        #uri: http://camunda.witcom-dev.services/engine-rest
        predicates:
         - Path=/camunda/**
        filters:
          - RewritePath=/camunda/(?<segment>.*), /engine-rest/$\{segment}
#httpbin
      - id: dummy-api
        uri: http://httpbin.org:80
        predicates:
         - Path=/get/**
        filters:
          - KeyCloakFilter=requiredRole,rmdb-resource-server:base-work
          #- AddRequestHeader=X-Some-Header, custom-header
          #- CommandFilter
#mcp
      - id: mcp-default
        uri: ${application.mcp-config.base-url}
        predicates:
         - Path=/mcp/**
        filters:
         - name: KeycloakMcpFilter
           args:
             resource-id: mcp-resource-server
             role-work: super-work
             role-read: read
         - RewritePath=/mcp/(?<segment>.*), /$\{segment}
#command    
      - id: command-base
        uri: ${RMDB_BASEURL:http://localhost:8080/axis}
        predicates:
         - Path=/rmdb/api/rest/entity/campus/**,/rmdb/api/rest/entity/building/**,/rmdb/api/rest/entity/floor/**,/rmdb/api/rest/entity/room/**
        filters:
         - name: KeycloakCommandFilter
           args:
             resource-id: rmdb-resource-server
             role-work: base-work
             role-read: read
         - RewritePath=/rmdb/(?<segment>.*), /axis/$\{segment}
      - id: command-default
        uri: ${RMDB_BASEURL:http://localhost:8080/axis}
        predicates:
         - Path=/rmdb/**
        filters:
         - name: KeycloakCommandFilter
           args:
             resource-id: rmdb-resource-server
             role-work: super-work
             role-read: read             
         - RewritePath=/rmdb/(?<segment>.*), /axis/$\{segment}

application:
  command-config:
    enabled: false
    base-url: ${RMDB_BASEURL:http://localhost:8080}
    #user: ${RMDB_USER}
    #password: ${RMDB_PASSWORD}
    #group: ${RMDB_GROUP}
    #mandant: ${RMDB_MANDANT}
  keycloak-config:
    keycloak-realm-id: ${KEYCLOAK_REALM_ID:#{null}}
    keycloak-server-url: ${KEYCLOAK_SERVER_URL:#{null}}
  spl-config:
    enabled: true
    #the followign 4 lines are deprecated. use tenants config instead
    #spl-base-url: ${SPL_BASEURL:http://localhost:8080}
    #spl-tenant: ${SPL_TENANT}
    #spl-user: ${SPL_USER}
    #spl-password: ${SPL_PASSWORD} 
    tenants:
    - spl-base-url: ${SPL_BASEURL:http://localhost:8080}
      spl-user: ${SPL_USER}
      spl-password: ${SPL_PASSWORD} 
      spl-tenant: ${SPL_TENANT}
      tenant-name: TEST01
      default-tenant: true
    - spl-base-url: ${SPL_BASEURL:http://localhost:8080}
      spl-user: ${SPL_USER}
      spl-password: ${SPL_PASSWORD} 
      spl-tenant: ${SPL_TENANT}
      tenant-name: TEST02

  mcp-config:
    enabled: false
    base-url: ${MCP_BASEURL:http://localhost:8080} 
    #user: ${MCP_USER:#{null}}
    #password: ${MCP_PASSWORD:#{null}}

logging:
  level:
    ROOT: INFO
    org.springframework.cloud.config: DEBUG
    feign.Logger: DEBUG

server:
  port: 8080
