spring:
  application:
    name: witcom-api-gateway
  cloud:
   gateway:
    globalcors:
      cors-configurations:
        '[/**]':
         allowedOrigins: "*"          


logging:
  level:
    root: ERROR
    de.witcom: DEBUG
