spring:
  redis:
    host: localhost
    port: 6379
    #password: bla
  cloud:
   gateway:
    globalcors:
      cors-configurations:
        '[/**]':
         allowedOrigins: "*"          
    routes:
#service-planet    
      - id: spl
        uri: ${SPL_BASEURL:http://localhost}/serviceplanet/remote/service
        predicates:
         - Path=/smdb/**
        filters:
         - KeyCloakFilter=requiredRole,service_read
         - ServicePlanetFilter
         - RewritePath=/smdb/(?<segment>.*), /serviceplanet/remote/service/$\{segment}
#dsl recherche
      - id: dsl-api
        uri: https://secure.mk-netzdienste.de/kundenportal
        predicates:
         - Path=/dslrecherche/**
        filters:
          - KeyCloakFilter=requiredRole,service_read
          - RemoveRequestHeader=Authorization    
          - BasicAuthFilter=${MK_USER},${MK_PASS}
          - RewritePath=/dslrecherche/(?<segment>.*), /kundenportal/$\{segment}
#camunda
      - id: camunda-rest-api
        uri: http://camundaengine:8080/engine-rest
        #uri: http://camunda.witcom-dev.services/engine-rest
        predicates:
         - Path=/camunda/**
        filters:
          - RewritePath=/camunda/(?<segment>.*), /engine-rest/$\{segment}
#httpbin
      - id: dummy-api
        uri: http://httpbin.org:80
        predicates:
         - Path=/get/**
        filters:
          - KeyCloakFilter=requiredRole,samplewebservice01:samplewebservice01_resource_a_read
          - AddRequestHeader=X-Some-Header, custom-header
    