---
version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      # [Optional] You can use build args to set options. e.g. 'VARIANT' below affects the image in the Dockerfile
      args: 
        VARIANT: 17-bookworm
        SKIP_APT_PEER_VERIFY: "true"
    env_file: .env
    volumes:
      # Forwards the local Docker socket to the container.
      # - /var/run/docker.sock:/var/run/docker-host.sock     
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace:cached

      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  

    user: vscode

    # Runs app on the same network as the service container, allows "forwardPorts" in devcontainer.json function.
    #network_mode: service
    network_mode: service:apigw_pause

  apigw_pause:
    image: k8s.gcr.io/pause
    hostname: pause
    container_name: apigw_pause

  apigw_redis:
    image: redis:6.0
    hostname: redis
    container_name: apigw_redis
    ports:
      - "6379:6379"
#    environment:

  apigw_keycloak:
    image: quay.io/keycloak/keycloak:21.1
    hostname: keycloak
    container_name: apigw_keycloak
    command: start-dev --import-realm
    ports:
      - "9999:9999"
    env_file: .env
    environment:
      - "KC_HTTP_PORT=9999"
      - "KC_PROXY=edge"
    volumes:
      - ./keycloak-import:/opt/keycloak/data/import

  apigw_mockserver:
    image: mockserver/mockserver:5.15.0
    hostname: mockserver
    container_name: apigw_mockserver
    ports:
      - "1080:1080"
    environment:
      # - "MOCKSERVER_LOG_LEVEL=DEBUG"
      - "MOCKSERVER_INITIALIZATION_JSON_PATH=/expectations/[A-z0-9_]*.json"
      - "MOCKSERVER_WATCH_INITIALIZATION_JSON=true"
    volumes:
      - ./mockserver-expectations:/expectations
