#!/usr/bin/env bash

./bin/git/init-hooks

# pip config set global.trusted-host  "pypi.org files.pythonhosted.org pypi.python.org" --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org

cp -f ./.devcontainer/bash_aliases.sh ~/.bash_aliases

# Install the helm-unittest plugin
helm plugin install https://github.com/helm-unittest/helm-unittest.git

echo "Run chezmoi-init for the final touch...."
